sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.1.0.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.5.0
      gemfile: Gemfile
    - rvm: 2.4.3
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/activerecord42.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/ruby_2.2.2.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.1.0.0
      gemfile: gemfiles/jruby.gemfile
